version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "amplify-testing"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qw68yxyy2mts"
s3_prefix = "amplify-testing"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "FrontOrigin=https://main.d12jdcjhy5lmh.amplifyapp.com"
